Add BCP47 parser
dillonkearns/elm-bcp47-language-tag pull request #2
Opened 2023-08-13 10:54 UTC by miniBill

2023-09-01 17:41 UTC, miniBill commented
The type that is currently called `Country` and described as `ISO 3166-1 country code` is called `region` in BCP47, because it could also be an UM_M49 [1] numeric code.

My proposal is to rename it to `Region`.

[1] https://en.wikipedia.org/wiki/UN_M49

2023-09-27 17:52 UTC, dillonkearns commented
Looks good other than the two comments I made and the `elm-review` errors in the CI. I'll merge and release once that's resolved. Thanks for the PR @miniBill!

2023-09-27 22:56 UTC, miniBill commented
The `NoModuleOnExposedNames` errors are false positives, I can suppress them?

You said you wrote two comments but I can't see them?

With regards to releasing, I think it's valuable to first decide whether to merge #3 in the next major bump or not

2023-09-28 03:12 UTC, dillonkearns commented
@miniBill is this the problem that's causing the false positives? https://github.com/sparksp/elm-review-imports/issues/127

I don't like the idea of using suppressed errors for bugs - I try to avoid suppressing errors, I see the main use case for those as being adopting a rule in a large codebase where you can't fix everything at once. I'd rather turn off the rule temporarily with a comment that links to the GitHub issue and explains that it can be re-enabled once that fixed. Would you be up for adding that in this PR?

> With regards to releasing, I think it's valuable to first decide whether to merge https://github.com/dillonkearns/elm-bcp47-language-tag/pull/3 in the next major bump or not

Good idea, I'll hold off on releasing until we've discussed that.

2023-09-28 03:13 UTC, dillonkearns commented
> You said you wrote two comments but I can't see them?

I can see them from this page <https://github.com/dillonkearns/elm-bcp47-language-tag/pull/2>.

I see the comments like this in that page:
<img width="954" alt="Screenshot 2023-09-27 at 8 13 26 PM" src="https://github.com/dillonkearns/elm-bcp47-language-tag/assets/1384166/cf67c7be-ab69-48c5-a6d5-26b3a0649cf6">

2023-09-29 00:15 UTC, miniBill commented
(notice how it says "Pending" on top, it means they are not visible to me yet)
Both comments make sense, will do!

2023-09-29 15:03 UTC, dillonkearns requested changes

2023-09-29 15:03 UTC, dillonkearns commented on src/LanguageTag/PrivateUse.elm
> +fromStrings : List String -> PrivateUse
If I'm reading the spec correctly here, it looks like a private use tag needs to be 1-8 characters to be valid?

> composed of the letter x and a hyphen followed by subtags of one to eight characters each, separated by hyphens

https://en.wikipedia.org/wiki/IETF_language_tag#Syntax_of_language_tags

If so, it would be nice to validate that and only return a `PrivateUse` value if it is validated.

2023-09-29 15:03 UTC, dillonkearns commented on src/LanguageTag/Parser.elm
> +{-| This will attempt to parse the tag as a BCP47 tag. If it fails, it will construct a `LanguageTag` using `custom`, with no validation.
Could you add some `elm-verify-examples` in the docs for `parseLanguageTag` and `parseBcp47`? That would be helpful for making users more confident that they're using the right function for their use case.

2023-09-29 15:03 UTC, dillonkearns commented
> (notice how it says "Pending" on top, it means they are not visible to me yet)

Ah yes, sorry about that, I sent them off for review so should be good now!

2023-09-29 17:21 UTC, miniBill commented on src/LanguageTag/PrivateUse.elm
> +fromStrings : List String -> PrivateUse
Makes sense

2023-09-29 18:02 UTC, miniBill commented
Made the changes requested

2023-10-04 16:55 UTC, merged

2023-10-04 16:56 UTC, dillonkearns commented
Looks good, thank you for the PR @miniBill!

I'll let you follow up with #3 before I cut a new release.